services:
  - type: web
    name: kosge-backend
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true

  - type: web
    name: kos-frontend-kqxo
    runtime: static
    buildCommand: echo "No build needed"
    staticPublishPath: frontend/public
    branch: main
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.png
        name: Content-Type
        value: image/png
      - path: /*.jpg
        name: Content-Type
        value: image/jpeg
      - path: /*.jpeg
        name: Content-Type
        value: image/jpeg
      - path: /*.woff2
        name: Content-Type
        value: font/woff2
      - path: /*.woff
        name: Content-Type
        value: font/woff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
